apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: rabbitmq
    environment: dev
    tier: db  
  ports:
    - port: 5672  
      targetPort: 5672
---  
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: rabbitmq
    environment: dev
    tier: db
  ports:
    - port: 5672  
      targetPort: 5672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-statefulset
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    environment: dev
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      component: rabbitmq
      environment: dev
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        environment: dev
        tier: db
    spec:
      containers: 
      - name: rabbitmq
        image: rabbitmq:3
        volumeMounts:
        - name: rabbitmq  
          mountPath: /var/lib/rabbitmq
          env:
          - name: RABBITMQ_DEFAULT_USER
            value: roboshop
          - name: RABBITMQ_DEFAULT_PASS
            value: roboshop123
# this is pvc          
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi        